frankframework/frank-flow

src/main/java/org/ibissource/frankflow/api/FileApi.java
src/main/java/org/ibissource/frankflow/util/FileUtils.java

Een `PUT` op `/configurations/{configName}/files?path=testFolder` maakt een folder aan.
Folders kunnen niet verwijderd worden.

Add create dir endpoint

---

src/frontend/src/app/app.component.html
src/frontend/src/app/app.component.scss
src/frontend/src/app/app.component.ts
src/frontend/src/app/flow/palette/group/group.component.scss
src/frontend/src/app/flow/palette/palette.component.scss
src/frontend/src/app/flow/palette/search/search.component.scss
src/frontend/src/app/header/header.component.scss
src/frontend/src/app/header/settings/settings.component.html
src/frontend/src/app/shared/button/button.component.scss
src/frontend/src/app/shared/button/button.component.ts
src/frontend/src/app/shared/toggle/toggle.component.scss
src/frontend/src/assets/styles/_theme.scss
src/frontend/src/assets/styles/inputs.scss
src/frontend/src/assets/styles/ngx-smart-modal.scss
src/frontend/src/assets/styles/styles.scss

add darkmode feature and changed color variables to darkmode variables

add darkmode

---

src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts
src/frontend/src/app/shared/components/file-tree/file-tree.component.ts
src/frontend/src/app/shared/services/file.service.ts

Queue fix for multiple fetch bug (temporary fix)

---

frank-flow/src/frontend/package-lock.json
frank-flow/src/frontend/src/app/flow/options/options.component.html
frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/flow/palette/palette.service.ts
frank-flow/src/frontend/src/app/shared/components/button/button.component.scss
frank-flow/src/frontend/src/app/shared/models/element.model.ts
frank-flow/src/frontend/src/assets/styles/inputs.scss
frank-flow/src/frontend/tsconfig.json

This is a WIP feature but can be merged to show the things that are done allready.

Flow 299/attributes

---

frank-flow/src/frontend/src/app/header/settings/settings.component.html
frank-flow/src/frontend/src/app/shared/components/toggle/toggle.component.html

Fix saving the settings by switching arount the state change events

---

frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts

Keep the same cursor position after editor update

---

frank-flow/src/frontend/src/app/editor/explorer/explorer.component.ts
frank-flow/src/frontend/src/app/shared/services/code.service.ts

Fix bug and implement feature.
Closes #147

Feature 147/clear editor

---

frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts
frank-flow/src/frontend/src/app/shared/services/code.service.ts

improve null checks

---

frank-flow/src/frontend/src/app/flow/options/options.component.html
frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

Feature 151/save attributes

---

frank-flow/src/frontend/src/app/editor/explorer/add-dialog/add-dialog.component.ts
frank-flow/src/frontend/src/app/editor/explorer/explorer.component.ts
frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts
frank-flow/src/frontend/src/app/shared/services/code.service.ts

Bug 148/prevent overwrite new file

---

frank-flow/src/frontend/src/app/editor/explorer/add-dialog/add-dialog.component.ts
frank-flow/src/frontend/src/app/flow/options/options.component.html
frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/models/flowStructure.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/workers/flow-generator.worker.ts

Did some other things too :hihi:
Closes #152

Bug 152/create receivers

---

frank-flow/src/frontend/src/app/flow/canvas/canvas.component.ts
frank-flow/src/frontend/src/app/flow/flow.component.html
frank-flow/src/frontend/src/app/flow/flow.component.spec.ts
frank-flow/src/frontend/src/app/flow/flow.component.ts
frank-flow/src/frontend/src/app/shared/services/graph.service.ts

Feature 162/canvas size

---

frank-flow/src/frontend/src/app/editor/explorer/add-dialog/add-dialog.component.html

Feature 198/add modal focus on textfield

---

frank-flow/src/frontend/src/app/flow/options/options.component.html

Add new attribute on enter

---

frank-flow/src/frontend/src/app/flow/node/node.component.spec.ts
frank-flow/src/frontend/src/app/flow/node/nodes/exit.model.ts
frank-flow/src/frontend/src/app/flow/node/nodes/listener.model.ts
frank-flow/src/frontend/src/app/flow/node/nodes/node.model.ts
frank-flow/src/frontend/src/app/flow/palette/group/group.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/services/node-generator.service.ts

Remove default positions from nodes

---

frank-flow/src/frontend/src/app/flow/canvas/canvas.component.ts
frank-flow/src/frontend/src/app/flow/palette/group/group.component.html
frank-flow/src/frontend/src/app/flow/palette/group/group.component.ts
frank-flow/src/frontend/src/app/flow/palette/item/item.component.scss
frank-flow/src/frontend/src/app/flow/palette/palette.component.html
frank-flow/src/frontend/src/app/flow/palette/palette.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

Lock palette if errors are found in the xml

---

frank-flow/src/frontend/src/app/flow/palette/palette.component.ts

Fix making a new subscription after component is destroyed

---

frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/services/frank-doc.service.ts

fix frankdoc subscription

---

frank-flow/src/frontend/src/app/shared/components/file-tree/file-tree.component.ts

check for currentFile when switching

---

frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

Change forward paths if target name is changes, also change firstPipe

---

frank-flow/src/frontend/src/app/app.component.ts
frank-flow/src/frontend/src/app/editor/explorer/explorer.component.ts
frank-flow/src/frontend/src/app/shared/services/current-file.service.ts
frank-flow/src/frontend/src/app/shared/services/session.service.spec.ts
frank-flow/src/frontend/src/app/shared/services/session.service.ts

Add file to session and load file on boot

---

frank-flow/src/frontend/src/app/app.component.ts
frank-flow/src/frontend/src/app/shared/models/flow-generation-data.model.ts
frank-flow/src/frontend/src/app/shared/services/current-file.service.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

Fixes #252 
And code optimizations (SOLID)

Fix not updating flow when swithcing file.

---

frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts
frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts
frank-flow/src/frontend/src/assets/styles/_globals.scss

Feature #154/show selected pipe

---

frank-flow/src/frontend/src/app/editor/explorer/explorer.component.html
frank-flow/src/frontend/src/app/editor/explorer/explorer.component.ts
frank-flow/src/frontend/src/app/header/header.component.html
frank-flow/src/frontend/src/app/header/header.component.ts
frank-flow/src/frontend/src/app/shared/components/edit-dialog/edit-dialog.component.html
frank-flow/src/frontend/src/app/shared/components/edit-dialog/edit-dialog.component.scss
frank-flow/src/frontend/src/app/shared/components/edit-dialog/edit-dialog.component.spec.ts
frank-flow/src/frontend/src/app/shared/components/edit-dialog/edit-dialog.component.ts
frank-flow/src/frontend/src/app/shared/components/shared.module.ts
frank-flow/src/frontend/src/app/shared/services/file.service.ts
frank-flow/src/main/java/org/ibissource/frankflow/api/DirectoryApi.java
frank-flow/src/main/java/org/ibissource/frankflow/api/FileApi.java

closes #146 
Note that when deleting a file the folder wont switch to another file or show an empty editor.
Will make another issue for this.

Feature #146/rename directory and files

---

frank-flow/src/frontend/src/app/flow/palette/palette.component.html
frank-flow/src/frontend/src/app/flow/palette/search/search.component.html

Remove elements from palette that don't get used, and fix search

---

frank-flow/src/frontend/package-lock.json
frank-flow/src/frontend/package.json
frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts
frank-flow/src/frontend/src/app/flow/canvas/canvas.component.ts
frank-flow/src/frontend/src/app/flow/flow.component.ts
frank-flow/src/frontend/src/app/header/header.component.html
frank-flow/src/frontend/src/app/header/header.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

Closes #229 
Fixes #258 and check if directory is selected
Woops unrelated feature and bug together. Happens when it's late, and I forget to make a new branch.

Add undo/redo and fix click event on add-file button

---

frank-flow/src/frontend/src/app/flow/options/options.component.html
frank-flow/src/frontend/src/app/flow/options/options.component.scss
frank-flow/src/frontend/src/assets/styles/inputs.scss

Fix input row, fix scrollbar and add icon

---

frank-flow/src/frontend/src/app/flow/canvas/canvas.component.ts
frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/models/flow-structure-node.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/services/graph.service.ts
frank-flow/src/frontend/src/app/shared/services/node-generator.service.ts

make node generation work with uuid

---

frank-flow/src/frontend/src/app/app.component.html
frank-flow/src/frontend/src/app/app.component.ts
frank-flow/src/frontend/src/app/editor/editor.component.html
frank-flow/src/frontend/src/app/editor/editor.component.ts
frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts

fix bug with event emitters

---

frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts
frank-flow/src/frontend/src/app/shared/models/file.model.ts
frank-flow/src/frontend/src/app/shared/services/current-file.service.ts

add firstLoad boolean

---

frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/header/settings/options/default-settings.model.ts
frank-flow/src/frontend/src/app/header/settings/options/grid-configuration.ts
frank-flow/src/frontend/src/app/header/settings/settings.component.html
frank-flow/src/frontend/src/app/header/settings/settings.component.ts
frank-flow/src/frontend/src/app/header/settings/settings.model.ts

Add option for grid configuration and cleanup code

---

frank-flow/src/frontend/src/app/app.component.ts
frank-flow/src/frontend/src/app/editor/explorer/explorer.component.ts
frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts
frank-flow/src/frontend/src/app/flow/flow.component.html
frank-flow/src/frontend/src/app/flow/flow.component.ts
frank-flow/src/frontend/src/app/shared/enums/file-type.enum.ts
frank-flow/src/frontend/src/app/shared/services/current-file.service.ts
frank-flow/src/frontend/src/app/shared/services/session.service.ts

code session with sergi

---

frank-flow/src/frontend/src/app/header/settings/settings.component.html
frank-flow/src/frontend/src/app/shared/components/toggle/toggle.component.html

Fix order in which the events get called in settings

---

frank-flow/src/frontend/cypress/Frank/src/main/configurations/Example1/conf.xml
frank-flow/src/frontend/src/app/flow/flow.component.html
frank-flow/src/frontend/src/app/flow/flow.component.ts
frank-flow/src/frontend/src/app/shared/services/current-file.service.ts
frank-flow/src/frontend/src/app/shared/services/pan-zoom.service.spec.ts
frank-flow/src/frontend/src/app/shared/services/pan-zoom.service.ts

Add panzoom service and reset zoom on new file

---

frank-flow/src/frontend/cypress/Frank/src/main/configurations/Example1/Configuration.xml
frank-flow/src/frontend/src/app/shared/models/flow-structure-node.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

Add `flow` namespace to positions

---

frank-flow/src/frontend/src/app/flow/node/node.component.scss
frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/flow/options/options.component.html
frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/models/flow-structure-node.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts
frank-flow/src/frontend/src/assets/styles/inputs.scss

Add selection highlight in flow and add delete button in options

---

frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts
frank-flow/src/frontend/src/app/flow/node/node.component.scss
frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/services/pan-zoom.service.ts

Highlight node in canvas if cursor is in tag, also pan to it

---

frank-flow/src/frontend/src/app/header/modes/mode.service.ts
frank-flow/src/frontend/src/app/header/settings/options/default-settings.model.ts
frank-flow/src/frontend/src/app/header/settings/settings.component.html
frank-flow/src/frontend/src/app/header/settings/settings.model.ts
frank-flow/src/frontend/src/app/shared/services/session.service.ts

Add feature to make use of the edit mode used in last session

---

frank-flow/src/frontend/cypress/Frank/src/main/configurations/Example1/Configuration.xml
frank-flow/src/frontend/src/app/flow/canvas/canvas.component.ts
frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/components/file-tree/file-tree.component.ts
frank-flow/src/frontend/src/app/shared/models/flow-structure.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/services/node-generator.service.ts

Add an implicit first pipe to the flow if no firstPipe has been given

---

frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/models/flow-node-attribute.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

Remove surrounding whitespace when removing attribute

---

frank-flow/src/frontend/src/app/flow/actions/actions.component.html
frank-flow/src/frontend/src/app/flow/actions/actions.component.ts

fix: remove center canvas button which caused unpredictable behavior

---

frank-flow/src/frontend/cypress/Frank/.gitignore
frank-flow/src/frontend/src/app/flow/canvas/canvas.component.ts
frank-flow/src/frontend/src/app/flow/options/options.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

Fixes #495 
Fixes #489 
Closes #491 also workes for firstPipe

Fix bugs regarding forwards

---

pom.xml

Reverts ibissource/frank-flow#558

revert: bump log4j2.version from 2.17.1 to 2.17.2"

---

frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

feat: change around the x and y in editor

---

frank-flow/pom.xml

Reverts ibissource/frank-flow#610

revert: bump spring.version from 5.3.15 to 5.3.17"

---

frank-flow/src/frontend/src/app/flow/node/node.component.scss
frank-flow/src/frontend/src/app/flow/palette/item/item.component.scss

fix: add pointer to nodelist and make it not selectable

---

frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/header/configuration-settings/configuration-settings.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-namespace.service.spec.ts
frank-flow/src/frontend/src/app/shared/services/flow-namespace.service.ts

fix: automatically add namespace when needed

---

frank-flow/src/frontend/src/app/shared/services/layout.service.ts
frank-flow/src/frontend/src/app/shared/services/node-generator.service.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

feat: add listener as nested element to a receiver

---

frank-flow/src/frontend/src/app/explorer/explorer.component.html
frank-flow/src/frontend/src/app/explorer/explorer.component.ts
frank-flow/src/frontend/src/app/shared/components/confirm-dialog/confirm-dialog.component.html
frank-flow/src/frontend/src/app/shared/components/confirm-dialog/confirm-dialog.component.scss
frank-flow/src/frontend/src/app/shared/components/confirm-dialog/confirm-dialog.component.spec.ts
frank-flow/src/frontend/src/app/shared/components/confirm-dialog/confirm-dialog.component.ts
frank-flow/src/frontend/src/app/shared/components/shared.module.ts

feat: add generic confirm popup

---

frank-flow/src/frontend/cypress/Frank/src/main/configurations/Example1/Configuration.xml
frank-flow/src/frontend/src/app/shared/models/flow-structure-node.model.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

feat: add elements with active attribute as a node

---

frank-flow/src/frontend/src/app/flow/options/options.component.html
frank-flow/src/frontend/src/app/flow/options/options.component.ts

fix: disable available attributes select if none vailable

---

frank-flow/src/frontend/src/app/flow/canvas/canvas.component.ts

fix: implicit first pipe now works with receivers

---

frank-flow/src/frontend/src/app/shared/services/current-file.service.ts

fix: remove errors when swithcing file

---

pom.xml

build(deps): update cxf to 3.4.7

---

frank-flow/src/frontend/src/app/flow/node/node.component.html

fix: change sander name in badge to sender type

---

frank-flow/src/frontend/src/app/flow/palette/group/group.component.scss

fix: user can no longer select group name

---

frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

feat: add pan to node on nodes with no x and y in file

---

README.md

docs: add a demo video to the readme

---

frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

feat: make pan to node work with receivers

---

frank-flow/src/frontend/src/app/flow/palette/filter.pipe.ts
frank-flow/src/frontend/src/app/flow/palette/palette.component.html
frank-flow/src/frontend/src/app/shared/models/flow-structure.model.ts
frank-flow/src/frontend/src/app/shared/services/layout.service.ts

fix: remove exits from palete and flow

---

frank-flow/src/frontend/src/app/header/configuration-settings/configuration-settings.component.html
frank-flow/src/frontend/src/app/header/configuration-settings/configuration-settings.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

feat: add function to delete flow settings

---

frank-flow/src/frontend/src/app/header/header.component.html
frank-flow/src/frontend/src/app/header/header.component.ts

feat: add undo and redo buttons to header

---

frank-flow/src/frontend/src/app/shared/services/current-file.service.ts

fixes non-configuration file was classified as empty file bug

fix: non-configuration file was classified as empty file

---

frank-flow/src/frontend/src/app/flow/node/node.component.scss

fix: make node name bold

---

frank-flow/src/frontend/src/app/editor/monaco-editor/monaco-editor.component.ts

feat: show tabs and spaces in the text editor

---

frank-flow/src/frontend/src/app/flow/flow.component.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts

fix: make node moving consistant

---

frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

fix: parse error when mutiple senders have the same name

---

frank-flow/src/frontend/src/app/flow/node/node.component.html
frank-flow/src/frontend/src/app/flow/node/node.component.scss
frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/flow/node/nodes/node.model.ts
frank-flow/src/frontend/src/app/flow/node/nodes/receiver.model.ts
frank-flow/src/frontend/src/app/flow/palette/group/group.component.ts
frank-flow/src/frontend/src/app/shared/models/badge.model.ts
frank-flow/src/frontend/src/app/shared/models/flow-structure-node.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/services/node-generator.service.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

feat: add badges for the listeners

---

README.md

docs(readme): update readme for latest frankrunner

---

frank-flow/src/frontend/src/app/shared/services/current-file.service.ts

fix: when file is deleted the frankflow breaks

---

frank-flow/src/frontend/src/app/shared/models/flow-structure.model.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

feat: implement Validators, Wrappers and Nested Elements for Sender

---

frank-flow/src/frontend/src/app/flow/canvas/canvas.component.ts
frank-flow/src/frontend/src/app/flow/node/node.component.ts
frank-flow/src/frontend/src/app/flow/node/nodes/exit.model.ts
frank-flow/src/frontend/src/app/flow/node/nodes/node.model.ts
frank-flow/src/frontend/src/app/shared/models/flow-structure.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-namespace.service.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/services/node-generator.service.ts

feat: add implicit forwards

---

frank-flow/src/frontend/cypress/Frank/pom.xml
frank-flow/src/frontend/src/app/shared/models/flow-structure-node.model.ts
frank-flow/src/frontend/src/app/shared/models/flow-structure.model.ts
frank-flow/src/frontend/src/app/shared/services/flow-structure.service.ts
frank-flow/src/frontend/src/app/shared/workers/xml-to-flow-structure.worker.ts

876 validators in other elements will also get rendered in the flow

---

frank-flow/src/frontend/src/app/shared/services/node-generator.service.ts

fix: fix explicit forward to implicit exit

---

frank-flow/src/main/java/org/frankframework/frankflow/api/ApiExceptionHandler.java

Will always return a proper json response when an exception has occurred

Update ApiExceptionHandler to be the same as the frank!console
